### ISSUE TITLE
Kokoro should run on PRs

### ISSUE THREAD

**Issue by busunkim96** [googleapis/python-pubsublite#3]
It looks like the default Kokoro configs don't work for a private repository. Are you folks alright having no CI until this is made public? There is a way to [add Kokoro to a private repo](https://g3doc.corp.google.com/devtools/kokoro/g3doc/userdocs/general/github_private_repo.md?cl=head) but the secrets propagation takes a few days.

@dpcollins-google @anguillanneuf

**Comment by anguillanneuf** [comment]
Internal cl/341844961 fixed it after the repo became public.
